apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-nginx
  namespace: demo-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-nginx
  template:
    metadata:
      labels:
        app: demo-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: html
          mountPath: /usr/share/nginx/html
        command: ["/bin/sh"]
        args:
          - "-c"
          - |
            echo 'Hello from OpenShift!' > /usr/share/nginx/html/index.html && \
            nginx -g 'daemon off;'
      volumes:
      - name: html
        emptyDir: {}

