apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 8080  # Use high port to avoid root requirement
        volumeMounts:
        - name: cache
          mountPath: /var/cache/nginx  # writable volume for cache
        # Optional: avoid user directive warnings
        securityContext:
          allowPrivilegeEscalation: false
      volumes:
      - name: cache
        emptyDir: {}  # ephemeral volume, writable
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-demo
spec:
  selector:
    app: nginx-demo
  ports:
  - protocol: TCP
    port: 80       # external port
    targetPort: 8080  # container port
  type: ClusterIP

