apiVersion: v1
kind: Namespace
metadata:
  name: demo-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
  namespace: demo-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        ports:
        - containerPort: 8080  # non-root safe
        volumeMounts:
        - name: nginx-cache
          mountPath: /var/cache/nginx
      volumes:
      - name: nginx-cache
        emptyDir: {}  # writable ephemeral storage
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-demo
  namespace: demo-nginx
spec:
  selector:
    app: nginx-demo
  ports:
  - protocol: TCP
    port: 80       # external port
    targetPort: 8080  # container port
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nginx-demo
  namespace: demo-nginx
spec:
  to:
    kind: Service
    name: nginx-demo
  port:
    targetPort: 80
  tls:
    termination: edge
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-demo-app
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/YOUR_GITHUB_USER/YOUR_REPO.git'
    path: 'nginx-gitops'
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: demo-nginx

