apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-nginx
  namespace: demo-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-nginx
  template:
    metadata:
      labels:
        app: demo-nginx
    spec:
      initContainers:
      - name: init-html
        image: busybox
        command: ['sh', '-c', 'echo "Hello from OpenShift!" > /usr/share/nginx/html/index.html']
        volumeMounts:
        - name: nginx-html
          mountPath: /usr/share/nginx/html
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: nginx-cache
          mountPath: /var/cache/nginx
        - name: nginx-html
          mountPath: /usr/share/nginx/html
      volumes:
      - name: nginx-cache
        emptyDir: {}
      - name: nginx-html
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: demo-nginx
  namespace: demo-nginx
spec:
  selector:
    app: demo-nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: demo-nginx
  namespace: demo-nginx
spec:
  to:
    kind: Service
    name: demo-nginx
  port:
    targetPort: 80
  tls:
    termination: edge

