apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-httpd
  namespace: demo-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-httpd
  template:
    metadata:
      labels:
        app: demo-httpd
    spec:
      containers:
      - name: httpd
        # Use high port
        image: httpd:alpine
        command: ["httpd", "-DFOREGROUND", "-f", "/usr/local/apache2/conf/httpd.conf", "-k", "start"]
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: demo-httpd
  namespace: demo-nginx
spec:
  selector:
    app: demo-httpd
  ports:
  - protocol: TCP
    port: 80       # Route will use this
    targetPort: 8080
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: demo-httpd
  namespace: demo-nginx
spec:
  to:
    kind: Service
    name: demo-httpd
  port:
    targetPort: 80
  tls:
    termination: edge

