apiVersion: v1
kind: Namespace
metadata:
  name: demo-nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-demo
  namespace: demo-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-demo
  template:
    metadata:
      labels:
        app: nginx-demo
    spec:
      containers:
      - name: nginx
        # OpenShift-friendly Nginx image
        image: registry.access.redhat.com/ubi8/nginx-118:latest
        ports:
        - containerPort: 8080  # high port avoids root requirement
        volumeMounts:
        - name: nginx-cache
          mountPath: /var/cache/nginx
      volumes:
      - name: nginx-cache
        emptyDir: {}  # writable by non-root
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-demo
  namespace: demo-nginx
spec:
  selector:
    app: nginx-demo
  ports:
  - protocol: TCP
    port: 80       # external
    targetPort: 8080  # container port
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nginx-demo
  namespace: demo-nginx
spec:
  to:
    kind: Service
    name: nginx-demo
  port:
    targetPort: 80
  tls:
    termination: edge

